### ISSUE TITLE
Custom ShortNumber matcher is not working

### ISSUE THREAD

**Issue by wedens** [spray/spray#959] opened 2014-11-07 11:43 UTC
I created matcher for Short:
```scala
  object ShortNumber extends NumberMatcher[Short](Short.MaxValue, 10) {
    def fromChar(c: Char) = fromDecimalChar(c)
  }
```
Exception I get:
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Short
        at scala.runtime.BoxesRunTime.unboxToShort(BoxesRunTime.java:101)
        at api.Matchers$ShortNumber$.fromChar(Matchers.scala:7)
        at api.Matchers$ShortNumber$.fromChar(Matchers.scala:6)
        at spray.routing.PathMatchers$NumberMatcher.digits$1(PathMatcher.scala:345)
        at spray.routing.PathMatchers$NumberMatcher.apply(PathMatcher.scala:356)
        at spray.routing.PathMatchers$NumberMatcher.apply(PathMatcher.scala:335)
```
What am I doing wrong?

**Comment by sirthias** [comment] 2015-02-10 12:59
While the problem is fixed in spray at least the added test appears to be missing from Akka HTTP.

**Comment by jrudolph** [comment] 2015-02-10 14:28
Recreated as akka/akka#16814.

**Closed by jrudolph** 2015-02-10 14:28 UTC
Labels: Bug, Needs Porting to Akka-HTTP
