### ISSUE TITLE
GzipDecompressor may fail in caves

### ISSUE THREAD

**Issue by jrudolph** [spray/spray#937] opened 2014-09-30 13:44 UTC
Because it fails fatally for partially received Gzip headers. As Gzip headers are usually as small as 10 bytes, you need to work under severely restricted conditions to trigger this behavior.

This will be fixed in akka-http and may warrant a backport at some point or another.

**Comment by sirthias** [comment] 2015-02-09 11:04
While prioritizing spray maintenance tickets we decided that this ticket is not important enough to make the current cut. Since the problem is already fixed in akka-http we are closing this ticket now.
Please reopen if this thing is really an issue for your application.

**Closed by sirthias** 2015-02-09 11:04 UTC
Labels: Bug
