### ISSUE TITLE
Marshalling custom case class using Scala Spray httpx

### ISSUE THREAD

**Issue by Christewart** [spray/spray#1082] opened 2015-10-28 17:00 UTC
i'm trying to marshall a string into a custom case class that I have. Here is the code I am trying to use

```scala
object NflWeekJsonProtocol extends DefaultJsonProtocol {
  implicit object NflWeekFormat extends RootJsonFormat[NflWeek] {
    override def read(jsValue: JsValue) = {
      jsValue match {
        case JsString(string) => NflWeekFactory.factory(string)
        case _ => throw new RuntimeException("NFLWeek should always be reprsented by a JsString")
      }
    }
    override def write(week: NflWeek) = {
      JsString(week.toString)
    }
  }
}
import spray.httpx.SprayJsonSupport._
import NflWeekJsonProtocol._
    path("playerScore") {
      get {
        parameters('gsisId.as[String] ?, 'week.as[NflWeek] ?, 'playerId.as[String]).as(PlayerScoreRequest) {
          playerScoreRequest : PlayerScoreRequest =>

        }
      }
    }
```
and i'm getting the following error: 

```
[error] /home/chris/dev/suredbits-dfs/src/main/scala/com/suredbits/dfs/nfl/scoring/NflPlayerScoringService.scala:40: too many arguments for method parameters: (pdm: spray.routing.directives.ParamDefMagnet)pdm.Out
[error]         parameters('gsisId.as[String] ?, 'week.as[NflWeek] ?, 'playerId.as[String]).as(PlayerScoreRequest) {
[error]                   ^
[error] one error found
```

NflWeekJsonProtocol represents a way to serializes the case class NflWeek. I thought this was all I would be required to do to get this working, what am I missing? If I am not missing something, is this a bug inside of Spray?

**Comment by jrudolph** [comment] 2015-11-09 10:16
`SprayJsonSupport` only allows marshalling from and to HttpEntity. Putting JSON into parameters is somewhat unusual (but probably possible). 

I'm closing this here, as this is not a bug. If you still need help, please discuss it at the mailing list at http://groups.google.com/group/spray-user. Thanks!

**Closed by jrudolph** 2015-11-09 10:16 UTC
