### ISSUE TITLE
Rethink client-side SSL configuration or document how to use it with the request-level API

### ISSUE THREAD

**Issue by jrudolph** [spray/spray#407] opened 2013-07-31 09:26 UTC
A reason for changing it would be that SSL configuration seems to be the only part of the configuration that is passed as an implicit parameter. If there's no good reason to do it this way we should think about streamlining this part of configuration with the rest of it.

**Comment by sirthias** [comment] 2015-02-09 14:16
Duplicate of https://github.com/spray/spray/issues/721

**Closed by sirthias** 2015-02-09 14:16 UTC
Labels: Documentation, Improvement
